name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  font_awesome_flutter: ^10.7.0
  cloud_firestore: ^5.6.6
  image_picker: ^1.1.2
  intl: ^0.18.0
  flutter_launcher_icons: ^0.13.1
  sensors_plus: ^6.1.1

  google_maps_flutter: ^2.5.0
  geolocator: ^11.0.0
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"